version = 0.1
[default.deploy.parameters]
stack_name = "slack-issue-tracker"
resolve_s3 = true
s3_prefix = "slack-issue-tracker"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "NotionDatabaseId=\"6771710d450d47a08e6c45ddfe67e4ab\""
image_repositories = []
